#!/usr/bin/env bash

set -euo pipefail

# set default XDG_STATE_HOME when invoked via Automator
while getopts "d:" opt; do
  case "$opt" in
  d) : "${XDG_STATE_HOME:=$OPTARG}" ;;
  *) break ;;
  esac
done

cd ~

histfile=${XDG_STATE_HOME:?}/bash_history
seshdir=${XDG_STATE_HOME:?}/bash_sessions/

mkdir -p "$seshdir"

if [ -f .bash_history ]; then
  cat .bash_history >> "$histfile"
  rm .bash_history
fi

if [ -d .bash_sessions ]; then
  mv .bash_sessions/* "$seshdir"
  rm -rf .bash_sessions
fi

sudo sed -i '' -e $'s| *SHELL_SESSION_DIR="$HOME/.bash_sessions"|HISTFILE="'"${XDG_STATE_HOME:?}"'/bash_history"\nSHELL_SESSION_DIR="'"${XDG_STATE_HOME:?}"'/bash_sessions"|' /etc/bashrc_Apple_Terminal

echo "Restart the shell"
