#!/usr/bin/env bash

set -euo pipefail

# set default data_home when invoked via Automator
while getopts "d:" opt; do
  case "$opt" in
  d) : "${XDG_STATE_HOME:=$OPTARG}" ;;
  *) break ;;
  esac
done

cd ~

mkdir -p "${XDG_STATE_HOME:?}/bash/sessions/"

if [ -f .bash_history ]; then
  cat .bash_history >> "${XDG_STATE_HOME:?}/bash_history"
  rm .bash_history
fi

if [ -d .bash_sessions ]; then
  mv .bash_sessions/* "${XDG_STATE_HOME:?}/bash_sessions/"
  rm -rf .bash_sessions
fi

sudo sed -i '' -e $'s| *SHELL_SESSION_DIR="$HOME/.bash_sessions"|HISTFILE="'"${XDG_STATE_HOME:?}"'/bash_history"\nSHELL_SESSION_DIR="'"${XDG_STATE_HOME:?}"'/bash_sessions"|' /etc/bashrc_Apple_Terminal

echo "Restart the shell"
