#!/bin/sh

# basing on sh instead of bash because it's likely that this is run for the
# first time on machines with a stock (old) version of bash.
set -eu

cd "${HOME}"

[ -d dotfiles ] || { # assume dotfiles existence is configured
  echo "==> Configuring Dotfiles…"
  git clone --no-checkout https://github.com/jasonkarns/dotfiles.git
  (
    cd dotfiles
    git config core.worktree "$HOME"
    git config core.sparseCheckout true
    printf '/*\n!readme.md' | git sparse-checkout set --stdin
    git config alias.regit '!echo "gitdir: dotfiles/.git" > ~/.git'
    git config alias.ungit '!rm ~/.git'
    git checkout main
    git submodule update --init --recursive

    { git remote get-url origin | grep -q 'git@github.com'; } ||
      git remote set-url origin git@github.com:jasonkarns/dotfiles.git
  )
}


command -v brew || {
  echo "==> Installing Homebrew…"
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
}

localconf='.config/bashrc.d/config.sh.local'
[ -f "$localconf" ] || {
  echo "==> Scaffolding ${localconf}…"
  cat > "$localconf" <<-'TMPL'
	# vi: ft=bash
	#
	# machine-specific and sensitive config
	# this file is not versioned
	
	for config in "${XDG_CONFIG_HOME:?}"/bashrc.d/*.sh.mac; do
	  test -r "$config" && . "$config"
	done
	
	printf -v CODEPATH -- "${HOME:?}/Projects/%s:" '' bats nodenv rbenv td
	
	# probably add some env vars like NPMJS_AUTHTOKEN and GHPR_AUTHTOKEN
TMPL
}

localconf='.ssh/config'
[ -f "$localconf" ] || {
  echo "==> Scaffolding ${localconf}…"
  cat > "$localconf" <<-'TMPL'
	# https://github.com/drduh/YubiKey-Guide#optional-save-public-key-for-identity-file-configuration
	
	Host github
	  IdentityFile ~/.ssh/id_rsa_yubikey_C0D44FDCF5A289F2.pub
	
	Include config.stribika
TMPL
}

localconf='.config/git/config.local'
[ -f "$localconf" ] || {
  echo "==> Scaffolding ${localconf}…"
  cat > "$localconf" <<-'TMPL'
	[include]
	  path = config.mac
	
	[includeIf "gitdir:~/Projects/"]
		path = config.projects
	
	# vi: ft=gitconfig
TMPL
}

. .profile
dotfiles/update
