#!/usr/bin/env bash

set -euo pipefail

cd "${HOME}"

[ -d dotfiles ] || { # assume dotfiles existence is configured
  git clone --no-checkout --recurse-submodules https://github.com/jasonkarns/dotfiles.git

  echo "==> Configuring Dotfiles…"
  cd dotfiles
  git config core.worktree "$HOME"
  git config core.sparseCheckout true
  printf '/*\n!readme.md' | git sparse-checkout set --stdin
  git config alias.regit '!cp ~/{,.}git'
  git config alias.ungit '!rm ~/.git'
  git checkout main
}


localconf='.config/bashrc.d/config.sh.local'
[ -f "$localconf" ] || {
  echo "==> Scaffolding ${localconf}…"
  cat > "$localconf" <<'TMPL'
# vi: ft=bash
#
# machine-specific and sensitive config
# this file is not versioned

for config in "${XDG_CONFIG_HOME:?}"/bashrc.d/*.sh.mac; do
  test -r "$config" && . "$config"
done

# probably add some env vars like NPMJS_AUTHTOKEN and GHPR_AUTHTOKEN
TMPL
}

# Install homebrew
command -v brew &>/dev/null || {
  echo "==> Installing Homebrew…"
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
}

dotfiles/update
