#!/bin/bash

set -euo pipefail
cd ~

confirm() { read -rp "Press any key to continue anyway or Ctrl-C to quit"; }

export HOMEBREW_VERBOSE=${VERBOSE-}
S=1

updots() {
  echo "==> Updating Dotfiles…"
  ( cd dotfiles && git pull --ff-only )

  if [ -e .bash_history ] || [ -e .bash_sessions ]; then
    echo "==> Fixing Shistory…"
    dotfiles/fix-apple-history
  fi
}

upbrew() {
  echo "==> Brewing…"
  brew doctor || confirm
  brew update # still necessary for taps

  echo "==> Checking Homebrew dependencies…"
  brewfile | brew bundle check --file=- ${S:+--quiet} || {
    echo "==> Installing Homebrew dependencies…"
    brewfile | brew bundle install --file=- ${S:+--quiet}
  }

  echo "==> Updating Homebrew dependencies…"
  brew outdated
  brew upgrade ${S:+--quiet}
  brew autoremove
  fix_completions
}

brewfile() {
  cat ~/.config/Brewfile{.local,} || true
}

fix_completions() {
  echo "==> Fixing shell completions…"
  ln -sf "${HOMEBREW_PREFIX:=$(brew --prefix)}/opt/fzf/shell/completion.bash" "${BASH_COMPLETION_COMPAT_DIR:?}/fzf"
  # TODO remove once confirmed we're done with hub
  rm -f "${BASH_COMPLETION_COMPAT_DIR:?}"/hub.*
}

case ${1:?which target?} in
brew|dots) up"$1" ;;
*) echo "unknown: '$1'" >&2; exit 1 ;;
esac
