#!/bin/bash

set -euo pipefail
cd ~

clone_repos() { while read -r repo; do git clone "https://github.com/$repo.git"; done; }
confirm() { read -rp "Press any key to continue anyway or Ctrl-C to quit"; }

export HOMEBREW_VERBOSE=${VERBOSE-}
S=1

updots() {
  echo "==> Updating Dotfiles…"
  ( cd dotfiles && git pull --ff-only )

  if [ -e .bash_history ] || [ -e .bash_sessions ]; then
    echo "==> Fixing Shistory…"
    dotfiles/fix-apple-history
  fi
}

upbrew() {
  echo "==> Brewing…"
  brew doctor || confirm
  brew update # still necessary for taps

  echo "==> Checking Homebrew dependencies…"
  brewfile | brew bundle check --file=- ${S:+--quiet} || {
    echo "==> Installing Homebrew dependencies…"
    brewfile | brew bundle --file=- --no-lock ${S:+--quiet}
  }

  echo "==> Updating Homebrew dependencies…"
  brew outdated
  brew upgrade ${S:+--quiet}
  brew autoremove
  fix_completions
}

brewfile() {
  cat ~/.config/Brewfile{.local,} || true
}

fix_completions() {
  echo "==> Fixing shell completions…"
  ln -sf "${HOMEBREW_PREFIX:=$(brew --prefix)}/opt/fzf/shell/completion.bash" "${BASH_COMPLETION_COMPAT_DIR:?}/fzf"
  # TODO remove once confirmed we're done with hub
  rm -f "${BASH_COMPLETION_COMPAT_DIR:?}"/hub.*
}

uprbenv(){
  make rbenv
}

upnodenv(){
  make nodenv
}

upvim(){
  echo "==> Setting up vim…"
  vim +PluginUpdate +PluginClean +qall
}

upnpm(){
  echo "==> Updating npm…"
  NODENV_VERSION=system npm update -g ${S:+--quiet}
}

upgpg(){
  if command -v keybase; then echo "==> Updating keybase/gpg…"
    keybase pgp pull
  else
    echo "==> Skipping keybase…"
  fi
}

upprefs(){
  dotfiles/prefs
}


# update all by default
if [ $# = 0 ]; then set -- dots brew rbenv nodenv vim npm gpg prefs; fi

while [ $# -gt 0 ]; do
  case $1 in
  dots|brew|rbenv|nodenv|vim|npm|gpg|prefs) up"$1" ;;
  *) echo "unknown: '$1'" >&2; exit 1 ;;
  esac
  shift
done
