---
# BUNDLE_DISABLE_LOCAL_BRANCH_CHECK: true
# BUNDLE_DISABLE_MULTISOURCE: true
BUNDLE_ERROR_ON_STDERR: true
BUNDLE_IGNORE_FUNDING_REQUESTS: true
BUNDLE_INIT_GEMS_RB: false
# BUNDLE_LOCAL__RAKE_TO_RULE_THEM_ALL: /Users/jasonkarns/Projects/rake_to_rule_them_all
BUNDLE_UPDATE_REQUIRES_ALL_FLAG: true

# gem scaffolding options
BUNDLE_GEM__CI: github
BUNDLE_GEM__CHANGELOG: false
BUNDLE_GEM__COC: true
BUNDLE_GEM__GITHUB_USERNAME: jasonkarns
BUNDLE_GEM__LINTER: standard
BUNDLE_GEM__MIT: true
BUNDLE_GEM__TEST: rspec

# native ext options
BUNDLE_BUILD__MYSQL2: "--with-opt-dir=/opt/homebrew/opt/openssl@3 --with-ldflags=-L/opt/homebrew/opt/zstd/lib"
BUNDLE_BUILD__NOKOGIRI: ""
BUNDLE_BUILD__PG: "--with-pg-config=/opt/homebrew/opt/libpq/bin/pg_config"
