#!/usr/bin/env bash

if [ "$1" = --about ]; then
  cat <<-ABOUT
  Prints a message if relevant files have been modified that might necessitate a command being run.
  i.e. npm-install for package.json or rake db:migrate for db/schema.rb, etc
ABOUT
  exit
fi

old_head_ref=$1
new_head_ref=$2

null_ref=0000000000000000000000000000000000000000

magenta="\\033[1;31m"
cyan="\\033[0;37m"
reset="\\033[0m"

initial_checkout() {
  test "$old_head_ref" = "$null_ref"
}

modified_files() {
  if initial_checkout; then
    git ls-files -- "$@"
  else
    git diff-tree --name-only --no-color -m "$old_head_ref" "$new_head_ref" -- "$@"
  fi
}

modified() {
  test -n "$(modified_files "$@")"
}

remind() {
  local file=$1
  local cmd=$2

  printf "\\n${magenta}> %s modified, run: \`${cyan}%s${magenta}\`${reset}\\n" "$file" "$cmd"
}

check() {
  local file="$1"
  local cmd="$2"
  shift 2
  local -a files=("$@")

  if modified "${files[@]}"; then
    remind "$file" "$cmd"
  fi
}


check Package 'npm install' npm-shrinkwrap.json package-lock.json

check Package 'yarn' yarn.lock

check Gemfile 'bundle' Gemfile Gemfile.lock

check Schema 'rake db:migrate' db/migrate db/schema.rb db/structure.sql
