# tap "codeclimate/formulae"
# tap "github/bootstrap"
# tap "homebrew/bundle"
# tap "homebrew/cask"
# tap "homebrew/cask-fonts"
# tap "homebrew/cask-versions"
# tap "homebrew/core", "git@github.com:Homebrew/homebrew-core.git"
# tap "homebrew/services"
# tap "nodenv/nodenv"
# tap "universal-ctags/universal-ctags"

# brew "adns"
# brew "icu4c"
# brew "autoconf"
# brew "automake"
# brew "openssl"
# brew "python"
brew "awscli"
brew "bash"
brew "bash-completion@2"
brew "bat"
brew "bats-core"
brew "brew-gem"
brew "bundler-completion"
# brew "chromedriver"
# brew "cmake"
# brew "composer"
brew "coreutils"
brew "csvkit"
brew "curl"
brew "docker-compose-completion"
brew "dos2unix"
# brew "doxygen"
# brew "elasticsearch@2.4", restart_service: true
brew "findutils"
brew "fish"
# brew "libpng"
brew "node"
brew "fx"
brew "fzf"
brew "gem-completion"
brew "gem-foreman"
brew "gem-github_changelog_generator"
# brew "libyaml"
brew "ruby"
brew "gem-md2man"
brew "gem-reek"
brew "gem-travis"
# brew "gettext"
# brew "ghi"
brew "gist"
# brew "git", args: ["with-curl", "with-openssl"]
brew "git-crypt"
brew "git-hooks", args: ["HEAD"]
brew "git-imerge"
brew "git-lfs"
# brew "go"
# brew "glide"
# brew "gmp"
# brew "gnu-tar"
# brew "libffi"
# brew "libtasn1"
# brew "libunistring"
# brew "gnutls"
# brew "libgcrypt"
# brew "libksba"
# brew "libusb"
# brew "pinentry"
brew "gnupg"
# brew "pth"
brew "gpg-agent"
brew "help2man"
brew "heroku"
# brew "highlight"
brew "hub"
# brew "hyperscan"
# brew "icdiff"
brew "unar"
# brew "ievms"
# brew "imagemagick"
# brew "jansson"
# brew "jemalloc"
# brew "jid"
# brew "oniguruma"
brew "jq"
brew "lastpass-cli"
# brew "launch_socket_server", restart_service: true
brew "launchctl-completion"
# brew "launchdns", restart_service: true
# brew "lcov"
# brew "libevent"
# brew "libxml2"
brew "lynx"
brew "mdcat"
# brew "memcached", restart_service: true
# brew "mkcert"
# brew "msgpack"
# brew "mysql@5.7", restart_service: true, link: true
# brew "pcre"
# brew "nginx", restart_service: true
# brew "pkg-config"
brew "nodenv"
# brew "nss"
brew "open-completion"
brew "openssh"
brew "tmux"
brew "overmind"
# brew "pidof"
# brew "postgresql", restart_service: true
# brew "protobuf"
brew "rails-completion"
brew "rake-completion"
# brew "rakudo-star"
brew "ruby-build"
brew "rbenv", args: ["HEAD"]
# brew "rbenv-bundler-ruby-version"
brew "reattach-to-user-namespace"
# brew "redis", restart_service: true
brew "ripgrep"
brew "ruby-completion"
brew "selecta"
brew "serveit"
brew "shellcheck", args: ["HEAD"]
# brew "slimerjs", args: ["HEAD"]
# brew "socat"
# brew "softhsm"
brew "ssh-copy-id"
brew "tealdeer"
brew "the_silver_searcher"
brew "tig"
brew "tmate"
brew "tree"
brew "vagrant-completion"
brew "vim"
brew "watch"
brew "wget"
brew "yarn-completion"
# brew "codeclimate/formulae/codeclimate"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]


cask "authy"
cask "betterzipql"
cask "colloquy"
cask "docker"
cask "dropbox"
cask "encryptme"
cask "firefox"
cask "font-fira-code"
cask "gitter"
# cask "gitx"
cask "google-chrome"
cask "google-drive"
cask "gpg-suite"
cask "grandperspective"
# cask "java"
cask "keybase"
cask "lastpass"
# cask "laullon-gitx"
cask "launchrocket"
cask "licecap"
cask "macvim"
cask "muzzle"
cask "ngrok"
cask "opera"
cask "paw"
# cask "pgadmin4"
# cask "picasa"
cask "postman"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlprettypatch"
cask "qlstephen"
cask "quicklook-json"
# cask "rowanj-gitx"
# cask "screenflow"
cask "sequel-pro"
cask "skype"
cask "suspicious-package"
cask "teamviewer"
# cask "time-out"
cask "trailer"
# cask "tunnelblick"
cask "webpquicklook"
# cask "xquartz"
cask "zoomus"

# vi: ft=ruby
