set nocompatible

source ~/.vim/vundles.vim
source ~/.vim/ui.vim
source ~/.vim/keys.vim

if executable('ag')
  " Use ag over grep
  set grepprg=ag\ --nogroup\ --nocolor

  if exists(':CtrlP')
    " Use ag in CtrlP for listing files
    let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'

    " ag is fast enough that CtrlP doesn't need to cache
    let g:ctrlp_use_caching = 0
  endif

endif

" automatically source vimrc if writing .vimrc or vimrc
" autocmd! BufWritePost .vimrc source $MYVIMRC
