# initially autogenerated by `$(brew --prefix fzf)/install`

# Setup fzf (skipped because PATH already added by homebrew)
# ---------
# if [[ ! "$PATH" == */opt/homebrew/opt/fzf/bin* ]]; then
#   PATH="${PATH:+${PATH}:}/opt/homebrew/opt/fzf/bin"
# fi

# Auto-completion (skipped because already symlinked into completion dir)
# ---------------
# [[ $- == *i* ]] && source "/opt/homebrew/opt/fzf/shell/completion.bash" 2> /dev/null

# Key bindings
# ------------
. "${HOMEBREW_PREFIX:=$(brew --prefix)}/opt/fzf/shell/key-bindings.bash"
