# initially autogenerated by /usr/local/opt/fzf/install
# setup removed because path already added by brew
# completion symlinked manually into /usr/local/etc/bash-completion.d/

# Key bindings
# ------------
source "/usr/local/opt/fzf/shell/key-bindings.bash"
