version: "1"
git_protocol: ssh
prompt: enabled
aliases:
    co: '!gh pr checkout "${1:-$(gh pr list -L100 | fzf | cut -f1)}"'
    prc: | # respects non-default HEAD: `git remote set-head origin other`
        !base="$(
          git symbolic-ref --short refs/remotes/origin/HEAD 2>/dev/null || true
        )"
        [ -z "$base" ] || set -- --base "${base#origin/}" "$@"
        gh pr create "$@"
