set nocompatible

" xdg setup
set backupdir=$XDG_CACHE_HOME/vim,/var/tmp,/tmp
set directory=$XDG_CACHE_HOME/vim,/var/tmp,/tmp
set viminfo+=n$XDG_CACHE_HOME/vim/viminfo
set runtimepath=$XDG_CONFIG_HOME/vim,$XDG_CONFIG_HOME/vim/after,$VIM,$VIMRUNTIME

source $XDG_CONFIG_HOME/vim/plugins.vim
source $XDG_CONFIG_HOME/vim/ui.vim
source $XDG_CONFIG_HOME/vim/keys.vim

if executable('ag')
  " Use ag over grep
  set grepprg=ag\ --nogroup\ --nocolor
endif

" automatically source vimrc if writing .vimrc or vimrc
" autocmd! BufWritePost .vimrc source $MYVIMRC

" plugin-specific configs loaded from $XDG_CONFIG_HOME/vim/after
