#! /usr/bin/env bash

# This script must be sourced.
# It will be sourced automatically by bash-completion if written to:
# - $(brew --prefix)/etc/bash_completion.d/ (for mac homebrew)
# - $BASH_COMPLETION_USER_DIR/completions/
# - $XDG_DATA_HOME/bash-completion

_cli_bash_autocomplete() {
    local cur opts
    cur="${COMP_WORDS[COMP_CWORD]}"
    opts=$( "${COMP_WORDS[@]:0:$COMP_CWORD}" --generate-bash-completion )
    mapfile -t COMPREPLY < <(compgen -W "${opts}" -- "${cur}")

    return 0
}

complete -F _cli_bash_autocomplete keybase
