---
install: --env-shebang --no-document --no-user-install

update: --env-shebang --no-document --no-user-install

pristine: --env-shebang

uninstall: --user-install

:sources:
- https://rubygems.org/
